### ISSUE TITLE
DHTbay and Bitcannon integration

### ISSUE THREAD

**Issue by crogers2287** [FlyersWeb/dhtbay#10]
Is there any chance you could go into more detail as to how to get these two communicating with each other? I can only get bitcannon to pull from what is listed in its config.json. How do I make it pull from dhtbay?

**Comment by peva3** [comment]
+1

**Comment by FlyersWeb** [comment]
You have to use my fork : https://github.com/FlyersWeb/bitcannon
You'll then need to edit api/config.json to use the correct mongo address.
Then follow instructions to install project and it's OK.

The projects communicates through the mongo database.

**Comment by peva3** [comment]
Is there anyway you could make a docker image of both in one. I tried setting it up the other day and just kept failing. It would really help me out and I think others too.

**Comment by FlyersWeb** [comment]
Should be resolved by dockerized version, that ease time to run investment

**Comment by FlyersWeb** [comment]
Hey, now bitcannon too is usable with docker : https://github.com/FlyersWeb/bitcannon/commit/191d1bcf828bfc2801f6c387a5fe513c093a92ed
