### ISSUE TITLE
Bittorrent-dht

### ISSUE THREAD

**Issue by simionrobert** [FlyersWeb/dhtbay#18]
Hi.

How does your algorithm manage to get announces of infohashes?
Bittorrent-dht is for getting peers and nodes and it announces when peers want to download metadata.

Thanks

**Comment by FlyersWeb** [comment]
By default it just listen to incoming peers request. To make it more efficient I usually manually announce a seeked torrent to get more traffic.

**Comment by simionrobert** [comment]
At what rate do you manage to crawl infohashes?

**Comment by FlyersWeb** [comment]
It depends on peers number but i can go up to 500 a day
