### ISSUE TITLE
Warning: API Request failed.

### ISSUE THREAD

**Issue by ghost** [FlyersWeb/dhtbay#20]
i installed the dht bay docker image then the bitcannon docker image. im getting errors in ssh saying .

ERROR: for mongo  Cannot create container for service mongo: b'Conflict. The container name "/mongo" is already in use by container "f8f87cdf0093d69789f65102f010ece48df05d0244207b9be1ad78bd9047e698". You have to remove (or rename) that container to be able to reuse that name.'

**Comment by FlyersWeb** [comment]
You should combine the 2 docker-compose files to be able to make them work together on the same computer. You'll notice that there is 2 mongo instances defined, you should remove the one that is useless

**Comment by ralyodio** [comment]
Can you tell us how to combine the two projects into one docker instance?
