### ISSUE TITLE
Download magnet diferent than expected.

### ISSUE THREAD

**Issue by duramato** [FlyersWeb/dhtbay#7]
The download magnet's trackers differ from the expected sources from the Sources table.
I don't know if this is intended, but it makes it hard for peering, even tough its avaiable on the DHT network very often those peers are hard to reach and often almost useless

**Comment by FlyersWeb** [comment]
This is more a https://github.com/feross/bittorrent-dht issue because we do not manage routing table out of the box

**Comment by FlyersWeb** [comment]
If you're talking about torrent file download, we do not download from peers because we only extract torrent metadata for database indexing, that's why we cannot use DHT routing table

**Comment by duramato** [comment]
The magnet that is presented on bitcannon and the sources
Ex:
Magnet link:
`
magnet:?xt=urn:btih:619dfb58452dda17f49097e7b12d8389e16b5d84&tr=udp%3A%2F%2Fopen.demonii.com%3A1337&tr=udp%3A%2F%2Ftracker.istole.it%3A80&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A80&tr=udp%3A%2F%2Ftracker.publicbt.com%3A80&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969&tr=udp%3A%2F%2Fexodus.desync.com%3A6969
`

Sources :

```
udp://tracker.coppersurfer.tk:6969/announce
udp://tracker.openbittorrent.com:80/announce
udp://glotorrents.pw:6969/announce
udp://tracker.publicbt.com:80/announce
http://retracker.local/announce
http://bt3.rutracker.cc/announce
```

If you notice the torrent trackers given on the magnet are not the ones "expected" that would come from a .torrent download.

**Comment by FlyersWeb** [comment]
I understand what you're telling, yes the torrent trackers on bitcannon comes from a static list in [L7](https://github.com/FlyersWeb/bitcannon/blob/master/api/config.default.json#L7). 
I didn't impacted too much original [bitcannon](https://github.com/stephen304/bitcannon) project but it would be great to add this feature.
This is more a bitcannon improvement by the way not related to dht-bay.

**Comment by duramato** [comment]
Would that be something you would be interesseted in adding to your bitcannon fork? As that would be something i would like to see and the original botcannon's development is sort of on iddle.
Also is there any reason why you don't have compiled releases of your [bitcannon] fork?

**Comment by FlyersWeb** [comment]
compiled version is never versioned, it's a bad practice. yes it would be an interesting feature but i'm not so good in Go programming and I've not so much time available right now. i'll let you know if I plan to work on this
