### ISSUE TITLE
crawlDHT.js never announces

### ISSUE THREAD

**Issue by kurttomlinson** [FlyersWeb/dhtbay#9]
When I run crawlDHT.js, it listens and gets ready, but it never proceeds to the next step. The output I get is below:

```
dht@dht-VirtualBox:~$ node /home/dht/dhtbay/crawlDHT.js
[Sun, 24 Jul 2016 01:10:32 GMT] { '0': 'now listening' }
[Sun, 24 Jul 2016 01:10:32 GMT] { '0': { address: '0.0.0.0', family: 'IPv4', port: 6881 } }
[Sun, 24 Jul 2016 01:10:37 GMT] { '0': 'now ready' }
```

**Comment by duramato** [comment]
You need to wait, it can take some time to connect to nodes and peers from my personal experience.

**Comment by kurttomlinson** [comment]
I've waited quite a while, at least ten minutes. How long should i expect to wait?

**Comment by FlyersWeb** [comment]
Maybe you need to allow 6881/udp port in your firewall

**Comment by kurttomlinson** [comment]
Yup, that was the problem. I needed to forward port 6881 on my router. Thanks!

**Comment by FlyersWeb** [comment]
Great, have fun, let me know if you need any more help

**Comment by albabosh** [comment]
I first started seeding something from aria2c for an hour or two to announce my node into dht, then I started crawldht.js & it ran well
